name: conchayoro-pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  PROJECT_NAME: "conchayoronew"
  MODULE_NAME: "backend"
  TAG: "latest"
  STACK_NAME: "64bit Amazon Linux 2 v3.5.7 running Docker"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk create-application --application-name $PROJECT_NAME --region $AWS_REGION
          aws elasticbeanstalk create-environment --application-name $PROJECT_NAME --environment-name $MODULE_NAME --solution-stack-name "$STACK_NAME" --region $AWS_REGION --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance

      - name: Configure AWS Elastic Beanstalk environment
        run: |
          eb init $PROJECT_NAME --region $AWS_REGION --platform "$STACK_NAME" --platform-version 3.5.7
          eb use $MODULE_NAME

      - name: Deploy application to Elastic Beanstalk
        run: |
          eb deploy $MODULE_NAME

      - name: Set up AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create ECR repository
        run: |
          aws ecr create-repository --repository-name $PROJECT_NAME/$MODULE_NAME --region $AWS_REGION

      - name: Build Docker image
        run: |
          docker build -t $PROJECT_NAME/$MODULE_NAME $MODULE_NAME/.

      - name: Tag Docker image
        run: |
          docker tag $PROJECT_NAME/$MODULE_NAME:$TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$PROJECT_NAME/$MODULE_NAME:$TAG

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$PROJECT_NAME/$MODULE_NAME:$TAG
